export interface LegalDocument {
  id: string;
  titleAr: string;
  titleEn: string;
  lastUpdatedAr: string;
  lastUpdatedEn: string;
  contentAr: string[];
  contentEn: string[];
}

export const LEGAL_DOCS: Record<string, LegalDocument> = {
  privacy: {
    id: "privacy",
    titleAr: "سياسة الخصوصية وحماية البيانات الشخصية",
    titleEn: "Privacy & Personal Data Protection Policy",
    lastUpdatedAr: "محدث وفق نظام حماية البيانات الشخصية السعودي (PDPL) لعام 2026",
    lastUpdatedEn: "Updated pursuant to the Saudi Personal Data Protection Law (PDPL) 2026",
    contentAr: [
      "مقدمة والتزام بالخصوصية: نولي في منصة 'ناصر أبو عبدالله' للوساطة والتسويق الرقمي أهمية قصوى لخصوصية وسرية بياناتكم المالية والشخصية. نلتزم بالمعايير الصارمة لنظام حماية البيانات الشخصية في المملكة العربية السعودية واللوائح التنظيمية الصادرة عن البنك المركزي السعودي (ساما).",
      "البيانات التي نقوم بجمعها: نجمع فقط البيانات الضرورية لدراسة مدى مطابقة شروط التمويل الشخصي الاسترشادي، وتشمل: الاسم الكريم، رقم الجوال، القطاع الوظيفي، صافي الراتب الشهري التقريبي، إجمالي الالتزامات الشهرية القائمة، والمدينة.",
      "الغرض من معالجة البيانات: تُستخدم هذه البيانات حصرياً لغرض تقديم الاستشارات التمويلية الاسترشادية، وحساب الأقساط والنسب التقديرية، وتوجيه العميل إلى القنوات والجهات التمويلية المعتمدة والمرخصة من ساما.",
      "أمن وتشفير البيانات: نطبق بروتوكولات حماية وتشفير متقدمة (256-bit SSL) لحماية كافة المراسلات والبيانات من أي وصول غير مصرح به أو تسريب.",
      "عدم البيع أو المشاركة: لا نقوم ببيع أو تأجير أو مقايضة بياناتك الشخصية مع أي طرف ثالث لأغراض تسويقية تجارية غير مرتبطة بطلبك.",
      "حقوق صاحب البيانات: يحق لك في أي وقت طلب تصحيح بياناتك أو الاستفسار عنها أو طلب مسحها من سجلاتنا عبر مراسلتنا الرسمية."
    ],
    contentEn: [
      "Introduction & Commitment: At Nasser Abu Abdullah Digital Brokerage, we adhere to the highest privacy standards in compliance with the Saudi Personal Data Protection Law (PDPL) and regulatory guidelines from the Saudi Central Bank (SAMA).",
      "Information Collected: We solely collect details strictly required for preliminary indicative loan evaluation, including legal name, contact phone, employment sector, approximate net monthly income, current debt commitments, and city.",
      "Purpose of Data Processing: Data collected is deployed exclusively to calculate indicative financing figures and guide applicants toward licensed SAMA financing partners.",
      "Data Security: High-level 256-bit encryption safeguards your communications against unauthorized access or exploitation.",
      "No Data Selling: We strictly never sell, rent, or lease your personal identifiers to third-party commercial marketing platforms.",
      "Subject Rights: You retain the lawful right to request review, update, correction, or deletion of your records via official communication channels."
    ]
  },
  terms: {
    id: "terms",
    titleAr: "الشروط والأحكام وميثاق الاستخدام",
    titleEn: "Terms of Service & Usage Charter",
    lastUpdatedAr: "ساري المفعول لعام 2026",
    lastUpdatedEn: "Effective as of 2026",
    contentAr: [
      "طبيعة الخدمة والصفة القانونية: منصة 'ناصر أبو عبدالله' هي منصة وساطة وتسويق رقمي مستقلة. المعلن ليس مصرفاً ولا مؤسسة تمويل مانحة للقروض، وإنما يقدم خدمات التوعية، وتسهيل الوصول، والربط بالجهات التمويلية المرخصة.",
      "أهلية الاستخدام: يشترط في مستخدم المنصة أن يكون مواطناً سعودياً كامل الأهلية القانونية، وأن تكون البيانات المدخلة صحيحة ودقيقة ومحدثة تماماً.",
      "الطبيعة الاسترشادية للحاسبة: جميع الأرقام والأقساط والنسب المعروضة في الحاسبة التفاعلية هي أرقام استرشادية تقريبية مبنية على معدلات الأرباح السائدة، ولا تعتبر بأي حال من الأحوال عرضاً مالياً ملزماً أو عقداً تمويلياً.",
      "حقوق الملكية الفكرية: جميع التصاميم، النصوص، المواد الإعلانية، والشعارات محمية بموجب أنظمة حماية حقوق المؤلف والعلامات التجارية في المملكة العربية السعودية.",
      "تعديل الشروط: يحق للمنصة تعديل هذه الشروط والأحكام بما يتوافق مع الأنظمة والتعليمات التنظيمية الصادرة من الجهات الإشرافية."
    ],
    contentEn: [
      "Nature of Service: The Nasser Abu Abdullah portal functions as an independent digital marketing and brokerage advisory interface. The advertiser is not a bank or direct lender, but rather facilitates access to licensed SAMA entities.",
      "User Eligibility: Users must be Saudi nationals holding full legal capacity, and all submitted data must be authentic and strictly accurate.",
      "Indicative Nature of Calculator: All metrics, calculations, and monthly payments generated by the on-site simulator represent approximate estimations and under no circumstances constitute a binding loan agreement.",
      "Intellectual Property: All creatives, graphical components, copy, and trademarks are protected under Saudi copyright and IP laws.",
      "Amendments: We reserve the right to revise terms in alignment with regulatory directives issued by relevant oversight bodies."
    ]
  },
  disclaimer: {
    id: "disclaimer",
    titleAr: "إخلاء المسؤولية المالي والتنظيمي وإفصاح الوساطة",
    titleEn: "Financial & Regulatory Disclaimer",
    lastUpdatedAr: "معتمد وفق تعليمات الإعلانات المالية المعتمدة من ساما",
    lastUpdatedEn: "Certified according to SAMA Financial Advertising Guidelines",
    contentAr: [
      "إفصاح الوساطة المستقلة: يعلن 'ناصر أبو عبدالله' صراحةً عن صفته كمعلن ومسوّق وساطة مالية مستقل (Independent Digital Advertiser). لا يمثل المعلن البنك المركزي السعودي ولا يدعي أنه جهة إقراض أو تمويل مباشرة.",
      "القرار الائتماني النهائي: القرار النهائي بالموافقة على التمويل، أو تحديد مبلغه النهائي، أو مدة سداده، أو معدل النسبة السنوي (APR)، أو الرسوم الإدارية، هو اختصاص حصري ومطلق للجهة التمويلية المرخصة من قبل البنك المركزي السعودي (الجهات والشركات التمويلية والبنوك الشريكة المعتمدة) وفقاً لتقييم السجل الائتماني (سمة) ونسبة عبء الدين (DBR).",
      "لا توجد موافقة مضمونة 100%: نرفض بشكل قاطع تقديم أي وعود مضللة أو ضمانات قاطعة بالحصول على التمويل دون اجتياز الدراسة الائتمانية النظامية للجهة الممولة.",
      "عدم فرض رسوم استشارة مسبقة: لا نطلب أي مبالغ مالية أو عمولات نقدية مسبقة من العملاء مقابل تقديم الاستشارات أو التوجيه التمويلي.",
      "التحذير من الاقتراض غير المسؤول: التمويل التزام مالي طويل الأجل. ينصح بمراجعة قدرتك على السداد وملاءمتك المالية قبل إبرام أي عقد تمويلي رسمي."
    ],
    contentEn: [
      "Brokerage Identity Disclosure: Nasser Abu Abdullah explicitly discloses his status as an independent digital advertiser and financial brokerage promoter. He does not claim to be a direct lender or banking entity.",
      "Final Underwriting Authority: The definitive decision to approve, modify, decline, or price any loan (including APR and administrative fees) remains the sole jurisdiction of SAMA-licensed financing companies pursuant to credit scoring (SIMAH) and debt burden ratios (DBR).",
      "No 100% Guaranteed Approvals: We strictly repudiate deceptive claims or absolute guarantees of loan approval without official underwriting.",
      "No Upfront Fees: We never solicit advance payments, consultation fees, or wire transfers for initial financial guidance.",
      "Responsible Borrowing Warning: Financing entails binding long-term commitments. Applicants must evaluate their debt capacity prudently prior to executing formal contracts."
    ]
  },
  protection: {
    id: "protection",
    titleAr: "مبادئ وقواعد حماية عملاء المؤسسات المالية (ساما)",
    titleEn: "SAMA Consumer Protection Principles",
    lastUpdatedAr: "ميثاق الشفافية والعدالة في المعاملات المالية",
    lastUpdatedEn: "Charter of Fairness & Transparency in Financial Services",
    contentAr: [
      "مبدأ المعاملة العادلة والمنصفة: يحظى كل عميل بمعاملة تتسم بالاحترام، والعدالة، والمساواة، والنزاهة المهنية في جميع مراحل تقديم الاستشارة التمويلية.",
      "مبدأ الإفصاح والشفافية: توفير معلومات واضحة، دقيقة، غير مضللة، ومكتوبة بلغة مفهومة حول مبالغ التمويل، شروط الأهلية، الرسوم الإدارية، وفترات السداد.",
      "مبدأ التثقيف والتوعية المالية: تقديم أدوات محاكاة ونماذج تساعد العميل على إدراك الأثر المالي للقسط الشهري على ميزانيته ونسبة عبء الدين المسموح بها نظاماً (33% إلى 45%).",
      "حماية البيانات والخصوصية: الحفاظ على أمن وسرية المعلومات الشخصية والمالية ومنع استغلالها لأي غرض غير مشروع.",
      "حماية حقوق العميل في التعاقد: حث العملاء دائماً على قراءة جدول الإفصاح المالي والعقد التمويلي الموحد كاملاً قبل التوقيع الرقمي مع الجهة الممولة."
    ],
    contentEn: [
      "Fair & Equitable Treatment: Every client is entitled to professional, equitable, dignified, and fair advisory across all interactions.",
      "Full Disclosure & Transparency: Delivery of transparent, accurate, and non-deceptive disclosures detailing loan limits, criteria, fees, and schedules.",
      "Financial Education & Literacy: Empowering borrowers with indicative calculators to comprehend the real budget impact and SAMA DBR compliance (33% to 45%).",
      "Privacy Safeguarding: Uncompromising security surrounding financial credentials against unauthorized processing.",
      "Contractual Transparency: Advocating that consumers meticulously read the unified loan disclosure schedule prior to electronic signing."
    ]
  },
  complaints: {
    id: "complaints",
    titleAr: "آلية الشكاوى والمقترحات والإبلاغ عن المخالفات",
    titleEn: "Complaints & Whistleblowing Procedure",
    lastUpdatedAr: "قنوات التواصل الرسمية لخدمة العملاء والشكاوى",
    lastUpdatedEn: "Official Customer Care & Escalation Channels",
    contentAr: [
      "قنوات رفع الشكاوى المباشرة: في حال وجود أي استفسار أو ملاحظة أو شكوى تتعلق بجودة الخدمة أو التعامل، نرحب بتواصلكم المباشر عبر الرقم المعتمد: 966580032068+ أو عبر الواتساب الرسمي.",
      "المدة الزمنية للمعالجة: نلتزم بدراسة الشكاوى والملاحظات الواردة والرد عليها خلال مدة أقصاها 48 ساعة عمل.",
      "الشكاوى المتعلقة بالعقود التمويلية: الشكاوى المتعلقة بالعقود، المبالغ المصروفة، أو الاعتراضات الائتمانية يجب توجيهها مباشرة إلى القنوات الرسمية للجهة التمويلية المتعاقد معها أو عبر منصة 'ساما تهتم' التابعة للبنك المركزي السعودي (www.samacares.gov.sa).",
      "النزاهة ومكافحة الاحتيال: نلتزم بأعلى معايير مكافحة الاحتيال المالي ونحذر من التجاوب مع أي حسابات غير رسمية لا تحمل بيانات الاعتماد الموضحة في هذه المنصة."
    ],
    contentEn: [
      "Direct Complaint Escalation: For inquiries, service observations, or feedback, please reach out via verified hotline +966580032068 or WhatsApp.",
      "Resolution Timeframe: We commit to reviewing and addressing inquiries within 48 business hours.",
      "Contractual Lending Disputes: Grievances regarding approved disbursements, loan agreements, or credit disputes must be directed to the official channels of the lending creditor or SAMA Cares platform (www.samacares.gov.sa).",
      "Anti-Fraud Integrity: We uphold rigorous anti-financial crime safeguards and caution the public against unauthorized impersonators."
    ]
  }
};
